= Red Hat Connectivity Link with Camel and SSO

:icons: font
:note-caption: :information_source:
:warning-caption: :warning:
:important-caption: :heavy_exclamation_mark:
:toc: left
:toclevels: 5

:url-rhcl-overview: https://developers.redhat.com/products/red-hat-connectivity-link/overview
:url-rhcl-getting-started: https://developers.redhat.com/articles/2024/06/12/getting-started-red-hat-connectivity-link-openshift
:url-rhcl-install-on-openshift: https://docs.kuadrant.io/0.8.0/kuadrant-operator/doc/install/install-openshift/
:url-rhcl-secure-n-connect: https://docs.kuadrant.io/0.8.0/kuadrant-operator/doc/user-guides/secure-protect-connect-single-multi-cluster/
:url-rhdh-lifecycle: https://access.redhat.com/support/policy/updates/developerhub


This readme provides instructions to install and configure RHCL ({url-rhcl-overview}[_Red Hat Connectivity Link_]) as
well as Red Hat build of Apache Camel in a repeatable manner. Once everything is configured, we will use this setup to
showcase RHCL integration with Camel and SSO.

== Prerequisites
RHCL depends on the following prerequisites:

. OpenShift cluster running on AWS
. `oc` command line tool is installed
. Logged in to OpenShift using the `oc` client
. Access to a DNS domain (called a hosted zone in AWS Route53), different from the domain used for the OpenShift cluster
.. Top domain hosted zone should have NS records for the RHCL hosted zone
. The IAM user should have at least these permissions:
.. route53:ChangeResourceRecordSets
.. route53:ListResourceRecordSets
.. route53:GetHostedZone
.. route53:ListHostedZones
. `kamel` command line tool
.. _This is NOT a RHCL prerequisite but since we will be using Red Hat build of Apache Camel, having a kamel binary
on your system is also a prerequisite. Install the `kamel` binary from OCP `Command Line Tools` link._
. Clone this repository on your system
.. _Create an environment variable named `RHCL_DEMO_HOME` to point to the cloned directory._

[NOTE]
====
. _For more details on the prerequisites, follow the {url-rhcl-getting-started}[getting started article]._
. _The RHCL install and uninstall scripts makes use of `envsubst` command that is available on Mac and Linux._
====



== Setup environment variables

In a terminal run the following commands:

[source,bash,options="nowrap"]
----
cd $RHCL_DEMO_HOME      # <.>
cp env.template .env    # <.>
# update ".env" file with the correct values for all the variables

. ./.env                # <.>
----
<.> Change into the directory that contains the cloned repository code
<.> Copy the contents of `env.template` into `.env` file.
.. *_Update `.env` with the correct values for all the variables before running the next step_*
<.> Sets environment variables, from `.env` file, in the current environment


== Install and configure

This section provides information on installation and configuration of the following components:

. Installation of Red Hat build of Apache Camel
. Deployment of a REST application using Camel
. Installation of Red Hat Connectivity Link
. Configuration of Red Hat Connectivity Link

Run the following commands in a terminal:

[source,bash,options="nowrap"]
----
cd $RHCL_DEMO_HOME
./install.sh            # <.>
----
<.> This script will perform the following actions:
.. Installs a REST application using Kamel in OpenShift cluster
.. Installs Red Hat Connectivity Link
.. Secures the APIs and configures exposed by Red Hat Connectivity Link to route messages to Camel

[IMPORTANT]
*_Even though the script will finish in a few seconds, the application deployment will take around 10 minutes before
it is ready to process any messages_*



== Test RHCL integration with Camel (*_and SSO - WIP_*)

=== Test GET operation
To test the RHCL integration with Camel run the following command in a terminal:

[source,bash,options="nowrap"]
----
$RHCL_DEMO_HOME/secure_connect/test-camel-route-get.sh
----
This script performs a GET call to verify the connectivity status, _with a timeout of 300 seconds_


=== Test POST operation
To insert a new record in the application run the following command in a terminal:

[source,bash,options="nowrap"]
----
$RHCL_DEMO_HOME/secure_connect/test-camel-route-post.sh <person_id> <person_name>
----
This script invokes a POST call using the provided `person_id` and `person_name` values, to add a new person record
in the Camel application by sending the JSON body to the route exposed via RHCL


=== Test PUT operation
To update an existing record in the application run the following command in a terminal:

[source,bash,options="nowrap"]
----
$RHCL_DEMO_HOME/secure_connect/test-camel-route-put.sh  <person_id> <person_name>
----
This script invokes a PUT call that uses the provided `person_name` to update the name of the person associated
with the provided `person_id`, in the Camel application, by sending the JSON body to the route exposed via RHCL


=== Retrieve the records with GET call

Once the previous test is successful, execute the following command to retrieve all the persons from the application:

[source,bash,options="nowrap"]
----
curl -k "https://$(oc get httproute kamel-rest -n ${KAMEL_NS} -o=jsonpath='{.spec.hostnames[0]}')/api/person"
----



== Uninstall

To uninstall Red Hat Connectivity Link and Camel, run the following commands in a terminal:

[source,bash,options="nowrap"]
----
cd $RHCL_DEMO_HOME
./uninstall.sh                  # <.>
----
<.> This script performs following operations in the OpenShift cluster:
. Uninstalls RHCL config
. Uninstalls Red Hat Connectivity Link
. Uninstalls Camel


== References

* {url-rhcl-overview}[RHCL - Overview] +
* {url-rhcl-getting-started}[RHCL - Getting Started] +
* {url-rhcl-install-on-openshift}[RHCL - Installation] +
* {url-rhcl-secure-n-connect}[RHCL - Secure and connect APIs] +

