apiVersion: kuadrant.io/v1beta2
kind: AuthPolicy
metadata:
  name: "${CAMEL_ROUTE_NAME}-auth"
  namespace: "${CAMEL_NS}"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: "${CAMEL_ROUTE_NAME}"
  routeSelectors:
  - matches:
    - method: POST
      path:
        type: Exact
        value: /api/person
    - method: PUT
      path:
        type: Exact
        value: /api/person
  rules:
    authentication:
      keycloak-users:
        jwt:
          issuerUrl: ${OPENID_ISSUER_URL}

